[package]
name = "atproto-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5"
heck = "0.5"  # For case conversion (snake_case, PascalCase, etc.)

[[bin]]
name = "generate"
path = "src/main.rs"
